Make image manifest validation less restrictive

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -55,12 +55,12 @@ jobs:
           aws ecr batch-get-image --repository-name ${{ env.IMAGE_REPO_NAME }} \
             --image-ids imageTag=${{ env.IMAGE_TAG }} \
             --query 'images[].imageManifest' --output text > manifest.json
-          if grep -q 'vnd.oci.image.index.v1+json' manifest.json; then
-            echo "Manifest is valid."
+          if grep -q 'vnd.docker.distribution.manifest.v2+json' manifest.json; then
+            echo "Manifest is valid for AWS Lambda."
           else
-            echo "Manifest validation failed." && exit 1
+            echo "Manifest validation failed. Found: $(cat manifest.json)" && exit 1
           fi
-
+          
       - name: Check if Lambda Function Exists
         id: check-lambda
         run: |
